import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

const setupHtml = await readFile(new URL("../public/setup/index.html", import.meta.url), "utf8");
const setupJs = await readFile(new URL("../public/setup/setup.js", import.meta.url), "utf8");
const setupCss = await readFile(new URL("../public/setup/setup.css", import.meta.url), "utf8");
const presentHtml = await readFile(new URL("../public/present/index.html", import.meta.url), "utf8");
const presentJs = await readFile(new URL("../public/present/present.js", import.meta.url), "utf8");
const presentCss = await readFile(new URL("../public/present/present.css", import.meta.url), "utf8");
const pdfViewerHtml = await readFile(new URL("../public/present/pdf-viewer.html", import.meta.url), "utf8");
const pdfViewerJs = await readFile(new URL("../public/present/pdf-viewer.js", import.meta.url), "utf8");
const pdfViewerCss = await readFile(new URL("../public/present/pdf-viewer.css", import.meta.url), "utf8");
const moderatorHtml = await readFile(new URL("../public/moderate/index.html", import.meta.url), "utf8");
const moderatorJs = await readFile(new URL("../public/moderate/moderate.js", import.meta.url), "utf8");
const eventContextJs = await readFile(new URL("../public/event-context.js", import.meta.url), "utf8");
const landingHtml = await readFile(new URL("../public/index.html", import.meta.url), "utf8");
const englishLandingHtml = await readFile(new URL("../public/en/index.html", import.meta.url), "utf8");
const landingJs = await readFile(new URL("../public/landing/landing.js", import.meta.url), "utf8");
const landingCss = await readFile(new URL("../public/landing/landing.css", import.meta.url), "utf8");
const creatorJs = await readFile(new URL("../public/new/new.js", import.meta.url), "utf8");
const demoHtml = await readFile(new URL("../public/demo/index.html", import.meta.url), "utf8");
const englishDemoHtml = await readFile(new URL("../public/en/demo/index.html", import.meta.url), "utf8");
const demoJs = await readFile(new URL("../public/demo/demo.js", import.meta.url), "utf8");
const demoCss = await readFile(new URL("../public/demo/demo.css", import.meta.url), "utf8");

test("setup wizard keeps the admin token session-scoped and writes protected config", () => {
  assert.match(setupHtml, /lang="zh-Hant-TW"/);
  assert.match(setupHtml, /data-config-form/);
  assert.match(setupHtml, /href="\/present\/"/);
  assert.match(setupJs, /consumeAccessToken\("admin"\)/);
  assert.match(eventContextJs, /sessionStorage\.setItem\(key, access\)/);
  assert.doesNotMatch(setupJs, /localStorage/);
  assert.match(setupJs, /eventContext\.apiBase}\/admin\/config/);
  assert.match(setupJs, /method: "POST"/);
  assert.match(setupCss, /@media \(max-width: 820px\)/);
  assert.match(setupCss, /@media \(max-width: 560px\)/);
});

test("presenter view loads a safe deck URL and exposes responsive dashboard controls", () => {
  assert.match(presentHtml, /lang="zh-Hant-TW"/);
  assert.match(presentHtml, /data-deck-frame/);
  assert.match(presentHtml, /data-dashboard-toggle/);
  assert.match(presentHtml, /data-toolbar-toggle/);
  assert.match(presentHtml, /data-toolbar-peek/);
  assert.match(presentHtml, /data-toolbar-peek-label/);
  assert.match(presentHtml, /src="\/dashboard\/"/);
  assert.doesNotMatch(presentHtml, /data-audience-qr/);
  assert.match(presentJs, /fetch\(eventApi\("\/config"\)\)/);
  assert.match(presentJs, /\["http:", "https:"\]/);
  assert.match(presentJs, /!parsed\.username && !parsed\.password/);
  assert.match(presentJs, /isHostedPdf\(deckUrl\)/);
  assert.match(presentJs, /\/present\/pdf-viewer\?file=/);
  assert.match(presentJs, /call-in:pdf-page/);
  assert.match(presentJs, /parsed\.pathname === `\$\{eventContext\.apiBase\}\/deck\.pdf`/);
  assert.match(presentJs, /new ResizeObserver\(syncToolbarPeekPosition\)/);
  assert.match(presentJs, /toolbar-collapsed/);
  assert.match(presentCss, /--dashboard-pane-width/);
  assert.doesNotMatch(presentCss, /left:50%/);
  assert.match(presentCss, /@media \(max-width: 1024px\)/);
  assert.match(presentCss, /@media \(max-width: 720px\)/);
  assert.match(pdfViewerHtml, /data-pdf-canvas/);
  assert.match(pdfViewerHtml, /data-pdf-prev/);
  assert.match(pdfViewerHtml, /data-pdf-next/);
  assert.match(pdfViewerJs, /from "\/vendor\/pdfjs\/pdf\.mjs"/);
  assert.match(pdfViewerJs, /getDocument\(\{ url: fileUrl\.href, isEvalSupported: false \}\)/);
  assert.match(pdfViewerJs, /pdf\.getPage\(pageNumber\)/);
  assert.match(pdfViewerJs, /\["ArrowRight", "PageDown", " "\]/);
  assert.ok(pdfViewerJs.includes('/^\\/api\\/events\\/[a-f0-9]{32}\\/deck\\.pdf$/'));
  assert.match(pdfViewerCss, /place-items: center/);
  assert.match(pdfViewerCss, /max-height: 100%/);
});

test("moderator access is automatic for creators and accepts a full private link", () => {
  assert.match(moderatorHtml, /主持私密連結或存取碼/);
  assert.match(moderatorHtml, /不需要自己尋找存取碼/);
  assert.match(moderatorHtml, /主持權限不在公開講者網址裡/);
  assert.match(moderatorJs, /function moderatorToken\(value\)/);
  assert.match(moderatorJs, /new URLSearchParams\(parsed\.hash\.slice\(1\)\)\.get\("access"\)/);
  assert.match(moderatorJs, /\.\.\.\(token \? \{ Authorization: `Bearer \$\{token\}` \} : \{\}\)/);
  assert.match(moderatorJs, /async function bootstrap\(\)/);
});

test("hosted creator replaces the landing-page demo and returns public and private links", () => {
  assert.match(landingHtml, /lang="zh-Hant-TW"/);
  assert.match(landingHtml, /點一下，換成你的簡報/);
  assert.match(landingHtml, /data-open-creator/);
  assert.match(landingHtml, /data-create-form/);
  assert.match(landingHtml, /上傳 PDF/);
  assert.match(landingHtml, /最大 20MB/);
  assert.match(landingHtml, /data-presenter-link/);
  assert.match(landingHtml, /data-audience-qr/);
  assert.match(landingHtml, /data-setup-link/);
  assert.match(landingHtml, /data-moderator-link/);
  assert.match(englishLandingHtml, /Click to use your slides/);
  assert.doesNotMatch(landingHtml, /Call-in 只保留完成本場活動所需的資料/);
  assert.doesNotMatch(landingHtml, />CALL-IN</);
  assert.match(landingHtml, /https:\/\/buymeacoffee\.com\/mashbean/);
  assert.match(landingHtml, /請作者喝杯咖啡/);
  assert.match(landingHtml, /href="\/demo\/"/);
  assert.match(landingHtml, /直接進 Demo/);
  assert.doesNotMatch(landingHtml, /複製範例網址/);
  assert.match(landingHtml, /https:\/\/github\.com\/mashbean\/call-in/);
  assert.match(landingHtml, /交給 Agent 部署/);
  assert.match(landingHtml, /class="host-prompt"/);
  assert.match(landingHtml, /mashbean 有權不經事前通知/);
  assert.match(englishLandingHtml, /https:\/\/buymeacoffee\.com\/mashbean/);
  assert.match(englishLandingHtml, /Buy me a coffee/);
  assert.match(englishLandingHtml, /href="\/en\/demo\/"/);
  assert.match(englishLandingHtml, /Enter demo/);
  assert.doesNotMatch(englishLandingHtml, /Copy sample URL/);
  assert.match(englishLandingHtml, /Ask an agent to deploy/);
  assert.match(englishLandingHtml, /immediately and without prior notice/);
  assert.doesNotMatch(landingHtml, /Sponsors 即將開放|GitHub Sponsors 收款通道正在準備/);
  assert.doesNotMatch(englishLandingHtml, /Sponsors coming soon|GitHub Sponsors payment channel is being prepared/);
  assert.match(landingJs, /openCreator/);
  assert.match(landingJs, /button\.closest\("\[data-copy-scope\]"\)/);
  assert.match(landingJs, /navigator\.clipboard\.writeText\(copyValue\)/);
  assert.match(creatorJs, /fetch\("\/api\/events"/);
  assert.match(creatorJs, /new FormData\(form\)/);
  assert.match(creatorJs, /result\.presenterUrl/);
  assert.match(creatorJs, /result\.setupUrl/);
  assert.match(creatorJs, /result\.moderatorUrl/);
  assert.match(landingHtml, /建立者可直接開啟/);
  assert.match(landingHtml, /複製主持私密連結/);
  assert.match(landingCss, /@media \(max-width: 620px\)/);
  assert.match(landingCss, /\.principle-host \{ grid-column:1 \/ -1;/);
  assert.match(landingCss, /\.demo-launch/);
  assert.match(demoHtml, /https:\/\/mashbean\.net\/decks\/isf-0427\//);
  assert.match(demoHtml, /公開 Demo・每小時重置/);
  assert.match(demoHtml, /src="\/demo\/dashboard\/"/);
  assert.match(englishDemoHtml, /Public demo · resets hourly/);
  assert.match(englishDemoHtml, /src="\/en\/demo\/dashboard\/"/);
  assert.doesNotMatch(demoHtml, /只會在這個分頁增加|本機展示/);
  assert.doesNotMatch(demoJs, /data-difficulty|data-reaction/);
  assert.match(eventContextJs, /apiBase: hostedMatch \? `\/api\/events/);
  assert.match(eventContextJs, /demoMatch \? "\/api\/demo"/);
  assert.match(eventContextJs, /demoBase}\/audience\//);
  assert.match(demoCss, /\.demo-layout/);
  assert.match(demoCss, /display:inline-flex; align-items:center; justify-content:center/);
});
